# Basic config File

rdir: "/data/simVar"

dmid: "/home/data/damage/dmid"
dhigh: "/home/data/damage/dhigh"
dnone: "/home/data/damage/dnone"

ref_list: "/project2/data/simVar/EMNGDN.txt"

threads: 32
cov_values: [4]

tmp: "/home/tmp"
sample_file_read: "/data/sample_files/sample_id.txt"


###############################################################################
#
# Common config values
#
###############################################################################
#Add binary paths
seqkit_bin: "seqkit"
samtools_bin: "samtools"

leehom_bin: "leehom-1.2.17"

# Program parameters
# Threads
seqkit_threads: 16
extract_threads: 8
threads_16: 16
threads_4: 4
threads_8: 8
threads_32: 32
threads_64: 64
threads_128: 128

